# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: nice_nano_v2
    shield: ak3
    artifact-name: ak3_qwerty
  - board: nice_nano_v2
    shield: ak3
    cmake-args: -DCONFIG_LAYOUT=2
    artifact-name: ak3_engrammer
  - board: nice_nano_v2
    shield: ak3
    cmake-args: -DCONFIG_LAYOUT=3
    artifact-name: ak3_engrammer_shifted


