#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: benvallack
      url-base: https://github.com/benvallack
  projects:
   - name: zmk
     remote: benvallack
     revision: repeatrollfix-tapdance-macro-mouse-dongle
     import: app/west.yml
  self:
    path: config
