name: zmk

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with: 
      archive_name: "ak3"

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # allow workflow to commit to the repo
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ak3
        run-id: ${{ github.event.workflow_run.id }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ak3_*.uf2